package thesis.utils.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum MAIL_SENDER_TYPE {
    OTP("<!DOCTYPE html><html lang=\"vi\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Xác Nhận OTP</title><style> body {font-family: 'Arial', sans-serif;background-color: #f4f4f4;margin: 0;padding: 0;}  .email-container {max-width: 600px;margin: 20px auto;background: white;padding: 20px;border-radius: 8px;box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);}  .email-header {background-color: #0056b3;color: white;padding: 20px;border-top-left-radius: 8px;border-top-right-radius: 8px;text-align: center;font-size: 24px;}  .email-body {padding: 20px;text-align: left;line-height: 1.6;color: #333;}  .otp-code {display: block;text-align: center;font-size: 24px;margin: 20px auto;padding: 10px;background-color: #e9ecef;width: fit-content;border-radius: 5px;font-weight: bold;color: #d32f2f;letter-spacing: 5px;}  .instructions li {margin-bottom: 10px;}  .footer {font-size: 14px;text-align: center;color: #666;padding: 20px;background-color: #f8f9fa;border-bottom-left-radius: 8px;border-bottom-right-radius: 8px;}</style></head><body><div class=\"email-container\"><div class=\"email-header\">Mã xác thực OTP</div><div class=\"email-body\"><p>Bạn vừa yêu cầu mã OTP để xác thực tài khoản của mình. Vui lòng sử dụng mã sau:</p><div class=\"otp-code\">%s</div><p>Mã OTP này chỉ có hiệu lực trong vòng %d phút.</p><p>Nếu bạn không yêu cầu mã này, vui lòng bỏ qua tin nhắn này hoặc liên hệ ngay với chúng tôi qua địa chỉ email<strong>admin@gmail.com</strong>.</p></div><div class=\"footer\">© 2024 Thesis News</div></div></body></html>"),
    PASSWORD_CHANGED("<!DOCTYPE html><html lang=\"vi\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Thông Báo Thay Đổi Mật Khẩu</title><style> body {font-family: 'Arial', sans-serif;background-color: #f4f4f4;margin: 0;padding: 0;}  .email-container {max-width: 600px;margin: 20px auto;background: white;padding: 20px;border-radius: 8px;box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);}  .email-header {background-color: #0056b3;color: white;padding: 20px;border-top-left-radius: 8px;border-top-right-radius: 8px;font-size: 24px;text-align: center;}  .email-body {padding: 20px;text-align: left;line-height: 1.6;color: #333;}  .important {color: #d32f2f;font-weight: bold;}  .instructions li {margin-bottom: 10px;}  .footer {font-size: 14px;text-align: center;color: #666;padding: 20px;background-color: #f8f9fa;border-bottom-left-radius: 8px;border-bottom-right-radius: 8px;}</style></head><body><div class=\"email-container\"><div class=\"email-header\">Cập nhật mật khẩu thành công</div><div class=\"email-body\"><p>Nếu bạn không thực hiện thay đổi này, vui lòng liên hệ ngay với chúng tôi để bảo vệ tài khoản của bạn.</p><p><span class=\"important\">Thời gian thay đổi:</span> %s</p><p>Để bảo đảm an toàn cho tài khoản của bạn, chúng tôi khuyến khích bạn:</p><ul class=\"instructions\"><li>Đăng nhập và thay đổi mật khẩu nếu thay đổi này không phải do bạn thực hiện.</li><li>Liên hệ ngay với bộ phận hỗ trợ của chúng tôi qua địa chỉ email <strong>admin@gmail.com</strong>.</li></ul><div class=\"footer\">© 2024 Thesis News</div></div></body></html>");

    private final String template;
}
