import Header from "@/components/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Thesis News",
  description: "Generated by Thesis News",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="block">
          <Header />
          <div className="max-w-[1336px] m-auto block">
            <div className="justify-evenly flex-row flex">
              <div className="flex-auto block md:min-w-[728px] md:max-w-[728px]">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
