import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import Footer from "@/components/Footer";
import Head from "next/head";
import "react-toastify/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thesis News",
  description: "Generated by Thesis News",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <Head>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
